### ISSUE TITLE
copying (a) folia document(s) between folders generates an error message, and copies only one file

### ISSUE THREAD

**Issue by hennie** [proycon/flat#110]
The error message:

ValueError at /filemanagement/

Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Request Method: 	POST
Request URL: 	http://flat.science.ru.nl/filemanagement/
Django Version: 	1.10.6
Exception Type: 	ValueError
Exception Value: 	

Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Exception Location: 	/usr/lib/python3.4/json/decoder.py in raw_decode, line 359
Python Executable: 	/scratch2/www/flat/env/bin/uwsgi
Python Version: 	3.4.3
Python Path: 	

['.',
 '',
 '/scratch2/www/flat/env/lib/python3.4',
 '/scratch2/www/flat/env/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/flat/env/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/scratch2/www/flat/env/lib/python3.4/site-packages',
 '/scratch2/www/flat/etc/']

Server time: 	Thu, 13 Apr 2017 15:39:22 +0200

**Comment by proycon** [comment]
Should be fixed now, deploying on our server in Nijmegen now too
