### ISSUE TITLE
Documentation is unclear on uploading a document

### ISSUE THREAD

**Issue by borissmidt** [proycon/flat#116]
Dear,

I cannot seem to find any documentation on how to create a folia formatted document from a simple text file. Thus i cannot upload a starting file to use this tool.

Kind regards, Boris Smidt

**Comment by proycon** [comment]
Good point, I should provide more pointers in the FLAT documentation for people who are yet unfamiliar with FoLiA. Two tools can be used to get a preliminary FoLiA document from a text: 
* ucto (https://languagemachines.github.io/ucto), which is tokeniser, supports various languages, and can produce FoLiA XML
* rst2folia (part of https://pypi.python.org/pypi/FoLiA-tools), converts reStructuredText (so not really plaintext) to FoLiA. This one has the ability to preserve document structure like bulleted lists etc, it doesn't tokenize (but you can use ucto again for that)

This relates to issue #74 also, which proposes to integrate these tools as converter options in FLAT so you don't have to run it manually, but that has not been a priority yet thus-far so isn't implemented yet.

If you deal with a custom format, you can always write your own conversion script in Python using the FoLiA API (part of https://github.com/proycon/pynlpl , documentation: http://pynlpl.readthedocs.io/en/latest/folia.html)

**Comment by proycon** [comment]
I should also add, if you happen to work on Dutch data, you might want to consider Frog ()https://languagemachines.github.io/frog), it does all kinds of automated linguistic annotation (PoS, lemma, NER, etc) and can produce output in FoLiA XML (which you can load into FLAT again).

**Comment by borissmidt** [comment]
Now it is clear.

Thanks for mentioning Frogger, But i need a different kind of NER annotation. I might be able to use it once i have made my own tagged data. Its a chickens and eggs problem.
