### ISSUE TITLE
makemigrations not checked in

### ISSUE THREAD

**Issue by prinsherbert** [proycon/flat#117]
In general, apps have a folder migrations (same level as the static and templates folders) with migrations in them, as created by `django-admin makemigrations` and fine-tuned by the developer. This helps the deployer setting up the database, as it is not the deployer's responsibility to design the SQL-schema to be used. Obviously, the SQL schema is tightly coupled to the application logic, making it a developer responsibility.

[This line](https://github.com/proycon/flat/blob/master/settings.py#L481), however, suggests that creating the migrations is the responsibility of the user or *deployer*. I think the developer should create the migrations, and that they should be part of this repository.

Makemigrations is a developer tool to creating boilerplate code which might need finetuning. Relying on it during deployment is risky, as the exact behavior of the generated boilerplate code, might change due to new ideas and insights of django developers.

@proycon : after writing the e-mail, I thought you might prefer an issue. Sorry for sending this twice.

For reference, the `django.contrib.admin` does this as well: https://github.com/django/django/tree/master/django/contrib/admin/migrations

**Comment by proycon** [comment]
Hmm.. Thanks for the feedback, that is indeed a good point I hadn't considered yet. I'll commit the necessary migrations and adapt the documentation.

**Comment by prinsherbert** [comment]
Very good!
