### ISSUE TITLE
Enable deletion of previously applied annotations.

### ISSUE THREAD

**Issue by merijnbeeksma** [proycon/flat#120]
Not deletion of a token, but of the actual annotation. Would be optimal if this could be done by clicking on the token instead of going through the edit history (in case you want to change someone else's annotations or correct an old annotation, for example).

**Comment by proycon** [comment]
Assigning an empty correction class should delete the correction, I'll investigate.

**Comment by proycon** [comment]
Related bug #122 popped up; fixed now..

**Comment by proycon** [comment]
It seems this was never properly reimplemented in the major refactoring for FLAT v0.7; working on it now....

**Comment by proycon** [comment]
I'm adding a new ``[DELETE....] RESTORE ORIGINAL`` keyword to FQL to facilitate this.
