### ISSUE TITLE
FQL syntax error

### ISSUE THREAD

**Issue by merijnbeeksma** [proycon/flat#124]
Error occurs when trying to annotate a token. 
Context: this error started occurring with one specific annotator after annotating several documents successfully.

**Comment by proycon** [comment]
Moved actual FQL error to proycon/pynlpl#36, but i think more is going on here... the query shouldn't have been like this in the first place as there was not correction on that word yet, it's possibly a regression bug introduced with the latest FLAT upgrade. Investigating..

**Comment by proycon** [comment]
Fixed, released and deployed
