### ISSUE TITLE
unable to make annotations on phone

### ISSUE THREAD

**Issue by merijnbeeksma** [proycon/flat#126]
context: one annotator can click on words, but nothing happens. No annotation window, no error message. This happens when working on her phone.

**Comment by proycon** [comment]
I assume this applies to all documents and not a particular document/word?

What OS does his/her phone run and what browser does he/she use?

I have to add btw. that FLAT has not been optimized for use on phones in any way yet... Aside from this issue, the interface might not be convenient enough for phones at all yet, considering the small screen.

**Comment by proycon** [comment]
(closing due to lack of response/urgency, reopen if still relevant)
