### ISSUE TITLE
Get it running correctly, more information is needed

### ISSUE THREAD

**Issue by kleinias** [proycon/flat#133]
I installed flat by the commands from the manual:

```
virtualenv --python=python3 env 
. env/bin/activate
pip install FoLiA-Linguistic-Annotation-Tool
export PYTHONPATH=/home/bingobongo/code/flat/
export DJANGO_SETTINGS_MODULE=settings
django-admin migrate --run-syncdb
export PYTHONPATH=/home/bingobongo/code/flat/
export DJANGO_SETTINGS_MODULE=settings
django-admin migrate --run-syncdb
django-admin createsuperuser
```

with the default settings, without the raise error line. and then started the servers:
```
django-admin runserver &
foliadocserve -d "/home/bingobongo/code/flat/" -p 8080 --git 
```

If I go to "localhost:8000", I can log in to the created account and upload a file I converted to folia-xml. But then I get some error, before some submission.

![auswahl_013](https://user-images.githubusercontent.com/33533067/42480686-01abfb14-83df-11e8-9bd7-c7b6a7a5f0ef.png)

Looks similar to issue #128, but selecting twice is not required for me.
Is there something wrong with my configuration? 

If there is some help, let me know!

PS: And I have a problem, how to write a new set definition. I read the documentation, but its a little bit sparse, if one hasn't any idea. Have you anywhere an example, where I could get some idea from, how it could look in the end?

**Comment by proycon** [comment]
Sorry for the delay! Something seems wrong indeed, that ``__pycache__`` part in the URL should not be there at all. I assume it's not in the URL you explicitly access either? Did you set a ``BASE_PREFIX`` variable in your FLAT configuration? (I wonder if the __pycache__ somehow got injected through that variable, it's still a bit of mystery to me what could have caused it)

Is this the installation as provided by LaMachine or installed and configured from scratch?

**Comment by kleinias** [comment]
Ok... so the "pycache" comes into that because I took that as namespace and that was, what I saw now, that I could not choose something else at the site, when I should upload the file. The menu looked like this: 

![menu_021](https://user-images.githubusercontent.com/33533067/43132622-aef3aa84-8f3c-11e8-9662-2abbca295d7a.png)

Then I created a directory, and then I could choose all other directories in the working directory as namespace. I get the same error with another namespace instead of the pycache:

[installsettingsstart.zip](https://github.com/proycon/flat/files/2223338/installsettingsstart.zip)

All my installation procedure is here, its just the lines from the installation guide: install it with the install_script, the settings file modified and the lines to start in another script. you just would have to change the path. thats my setup.

![auswahl_022](https://user-images.githubusercontent.com/33533067/43134513-9a363642-8f42-11e8-93a9-3b1011478ebf.png)

**Comment by proycon** [comment]
Sorry it took a while again because of the holiday period. It seems you set the ``WORKDIR`` aka folia document root wrong, you have it pointing to the code, but it should be an (initially empty) directory where the FoLiA documents will be stored. That explains why you saw all those directories as possible namespaces.

Make sure to start foliadocserve with that same directory specified as document root.

I hope this gets you a bit further?

**Comment by kleinias** [comment]
I changed these paths. 
There was later another process listening on the port and doing some first step, but now I got it working :) thx.

I have a few questions:

Can I somehow import annotations from parsers?

Do you have some kind of documentation, how to build customized annotation schemes?

Is there a possibility to see my annotations as arcs?

And some note:
I get different error messages, if I don't do correct annotations, like: "TypeError: Cannot read property 'trim' of null". It would seem better to me, if that would point me to the error, that I did,  than some error in the program.

**Comment by proycon** [comment]
> Can I somehow import annotations from parsers?

FLAT uses the FoLiA format. Some parsers like [Frog](https://github.io/frog) output this natively, for some others there are converters (e.g. Alpino), for others you may need to implement a converter yourself. I'm planning on working on a converter from the CONNL-U format if that helps.

> Do you have some kind of documentation, how to build customized annotation schemes?

Yes, see the documentation on FoLiA Set Definitions, chapter 3 of the [FoLiA Documentation](https://github.com/proycon/folia/blob/master/docs/folia.pdf). Also see the examples in https://github.com/proycon/folia/tree/master/setdefinitions 

> Is there a possibility to see my annotations as arcs?

Not really at nicely visualised arcs no, the best we have is the visualisations you can toggle on/off in the global annotations menu.

> And some note:
> I get different error messages, if I don't do correct annotations, like: "TypeError: Cannot read property 'trim' of null". It would seem better to me, if that would point me to the error, that I did, than some error in the program.

Hmm yes, that sounds pretty uninformative, I'd consider it a bug, so feel free to open an issue on that one.

Also be aware that the default `Full` configuration of FLAT exposes a lot of functionality you don't need and which will confuse the annotator, make sure to customize your configuration to enable only those features you need (see the administration guide), I might have to ship some simpler configurations with FLAT out of the box.
