### ISSUE TITLE
adding new annotation types 

### ISSUE THREAD

**Issue by MouhamadAboShokor** [proycon/flat#136]
firstly many thanks for your hard work and cute product @proycon , one question if I may . 
Is there a way to define new annotation types i.e. not define a new folia set for say POS tagging but define a full new type say such as abusive phrase or something like that 
I failed to find a discription for that in either folia or flat documentation 
thanks alot

**Comment by proycon** [comment]
The annotation types are strictly defined by FoLiA itself (but the vocabulary thereof is not and are in the set definitions as you already noticed). There are various annotation types in FoLiA and it's likely one already fits your need. If you're looking for annotating multi-word phrases for example, then use the *entity* annotation type with a custom set definition that would for example define an abusive class, or whatever others you desire.

If you think there is really an important annotation type missing, then let me know and we can look into extending FoLiA itself to accommodate that.

**Comment by MouhamadAboShokor** [comment]
thanks a lot , it was my mistake I should have read FOLIA's paper , I guess this issue is resolved and could be closed
