### ISSUE TITLE
How to access alternative annotations in FLAT?

### ISSUE THREAD

**Issue by luutuntin** [proycon/flat#149]
Hi Maarten,

Here is my use case:

1. "Просто" is automatically tagged as `PART`.
<img width="348" alt="alternative_01" src="https://user-images.githubusercontent.com/11186240/59534287-d67c2700-8ebb-11e9-847e-a3edc0f6f97a.png">

2. The annotator suggests an alternative, `ADV`.
<img width="345" alt="alternative_02" src="https://user-images.githubusercontent.com/11186240/59534363-1d6a1c80-8ebc-11e9-84d6-9151511ba789.png">

3. We can see the annotation result.
<img width="302" alt="alternative_03" src="https://user-images.githubusercontent.com/11186240/59534456-5aceaa00-8ebc-11e9-9faa-2d3e3854ca33.png">

4. But how to access the alternative annotation to modify it in FLAT?
<img width="348" alt="alternative_04" src="https://user-images.githubusercontent.com/11186240/59534501-7c2f9600-8ebc-11e9-9c99-9cd5b04a87e7.png">

Best,
Alex

**Comment by proycon** [comment]
Good question, alternative annotation is still a bit underused and underdeveloped. I see the visualisation is also missing, and indeed editing the alternative. This will need to be developed.

**Comment by proycon** [comment]
I've implemented the viewing part for alternative annotations (not released/deployed yet), it will look as follows and require the new "show alternative annotations" toggle in the tools & options menu to be enabled, as by default it will be disabled:

![image](https://user-images.githubusercontent.com/75427/60889728-fbb14a80-a259-11e9-8cc2-c99600b06cfc.png)

Editing/removing alternative annotations requires some extra work still.

**Comment by proycon** [comment]
@luutuntin I have an additional question regarding your use case, you asked:

> But how to access the alternative annotation to modify it in FLAT?

I assume you mean you want to change the alternative annotation right? (and keep it as an alternative), this is the part I'd still have to implement. But I was thinking your question could perhaps also be interpreted as "I want to change the actual annotation (PART) to take the value of the alternative (ADV), which is something FoLiA/FLAT's suggestion-for-correction mechanism would be able to provide already (but another shortcut listing alternatives might be appropriate here too).

**Comment by luutuntin** [comment]
Thank you, the viewing part for alternative inline annotations looks great.
Yes, we want to be able to change the alternative annotation in FLAT, and in general, it is desirable that annotators can edit any information they have entered.

**Comment by proycon** [comment]
> it is desirable that annotators can edit any information they have entered.

Indeed, I completely agree.

**Comment by luutuntin** [comment]
> ![image](https://user-images.githubusercontent.com/75427/60889728-fbb14a80-a259-11e9-8cc2-c99600b06cfc.png)
>
In this example, I can see that both annotations of `domain` and `sense` are grouped together under the same `<alt>` element. Currently, if I try to add alternative `lemma` and `pos` at the same time by one click of `OK` at the bottom of **Annotation Editor** in FLAT, each of them will be put in a separate `<alt>` element. I just want to make sure that you are aware of this. (And I definitely prefer the behavior in your example, which is consistent with [the FoLiA documentation](https://folia.readthedocs.io/en/latest/alternative_annotation.html#alternative-inline-annotation).)

**Comment by proycon** [comment]
Right, that is a good point indeed. The current edit capabilities don't allow grouping alternatives yet, but I agree that grouping them when they are edited in the same edit session would be a good solution. I'll implement that.

**Comment by luutuntin** [comment]
Great.
