### ISSUE TITLE
Add the ability to edit the structure class

### ISSUE THREAD

**Issue by proycon** [proycon/flat#152]
When clicking a word or other structural element, you can only edit annotations under it, rather than the structural annotation itself. Implement a facility to edit the class (and underlying features) of the structural element.

Assigning classes and features to Figures may be relevant for @ErkanBasar and @sbrugman as an alternative to metric annotation (#151).

**Comment by proycon** [comment]
* [ ] Verify submission of structure class edit works

**Comment by luutuntin** [comment]
Hi Maarten, does this ability allow us, for example, to add a new sentence to a document opened in FLAT? If yes, how do we do that?

**Comment by luutuntin** [comment]
Oh, this ability is just for structure class annotation, such as different types of words or sentences, right? (And the task I asked in my previous message should be handled by Structure Editor, which in under development.)

**Comment by proycon** [comment]
Yes, precisely. There haven't been many requests for the structure editor yet (thought it's been proposed for a long time already), so if you're interesting I'll bump it a bit higher on the priority list?

**Comment by proycon** [comment]
(cross-referencing #5)

**Comment by luutuntin** [comment]
Thanks. On the one hand, we do have the real use cases that clearly benefit from the structure editors (e.g. a morphological annotator found out there was a whole utterance missing from transcription stage and therefore needed to add it to both the transcript (ELAN file) and the morphological annotation (FoLiA file)). On the other hand, these use cases are rare enough for manual handling.
