### ISSUE TITLE
How to handle "Loading aborted" warning?

### ISSUE THREAD

**Issue by luutuntin** [proycon/flat#153]
Hi Maarten,

When loading a big file to FLAT, we encounter the warning "_**Loading aborted**: There was too much data to display at once. Your are looking at a partial result. (Select a sub-part to visualise instead)_."
<img width="945" alt="loading_aborted" src="https://user-images.githubusercontent.com/11186240/62664758-bfe9cd80-b94a-11e9-98c3-7dc8eebb440a.png">

What is the best way to handle this case?

Best,
Alex

**Comment by proycon** [comment]
Instead of using the "full document" perspective you are in now, you can select another perspective on the data (use the selection box on the top-left), a common one is using the "sentence" perspective for instance (if that makes sense in your case). FLAT then shows a certain predefined number of sentences per page and offers pagination to go forward/backward.

**Comment by luutuntin** [comment]
In our case, the other perspective is "Utterance". When I select it, I encounter "_Error: No slices available for perspective utt. If you are the administrator, make sure to define this perspective in the slices in the configuration._"
![loading_aborted_2](https://user-images.githubusercontent.com/11186240/62701728-070ba900-b9b3-11e9-86da-905ff01f36b3.png)
It's not clear to me where in the configuration I can define this.

And I wonder if the error is the reason why I cannot see the pagination after clicking "OK".
![loading_aborted_3](https://user-images.githubusercontent.com/11186240/62702156-ff98cf80-b9b3-11e9-9166-51e6d722927a.png)

**Comment by proycon** [comment]
Right, utterance would be a good perspective. You need a little extra configuration to make it work I see. In your configuration (in ``settings.py``), you can set allowed perspectives and the default slices (number of elements) to show for the perspective. This looks as follows:

```
   'perspectives': ['utt'],
   'slices': 'utt:50',
```

(restart FLAT afterwards) 

I see the documentation may need to be made a bit clearer on this regard, and perhaps I should set a default so you don't encounter this error.

**Comment by luutuntin** [comment]
Thank you so much. We can view the whole document now.
<img width="960" alt="loading_aborted_4" src="https://user-images.githubusercontent.com/11186240/62734142-44ddf100-b9f6-11e9-8e63-525231650c02.png">

**Comment by proycon** [comment]
Great!
