### ISSUE TITLE
Unexpected and inconsistent login requirement for any actions in FLAT

### ISSUE THREAD

**Issue by luutuntin** [proycon/flat#154]
Hi Maarten,

Recently, whenever I deploy a new instance of FLAT (e.g. _`http://alexluu.csbrandeis.org/flat_latest`_) on my sandbox server, I frequently encounter this weird behavior from that FLAT instance.
For example, here is the interface after the login:
<img width="960" alt="login_required_01" src="https://user-images.githubusercontent.com/11186240/62743849-02c2a880-ba12-11e9-9677-e0e5fbae27be.png">

When I click the folder link 'luutuntin/', I receive inconsistent results: the next page can be the normal one (i.e. _`http://alexluu.csbrandeis.org/flat_latest/index/luutuntin`_) or the one requiring another login (i.e. _`http://alexluu.csbrandeis.org/flat_latest/login/?next=/flat_latest/index/luutuntin`_):
<img width="960" alt="login_required_03" src="https://user-images.githubusercontent.com/11186240/62744027-c774a980-ba12-11e9-898e-8d7536507412.png">

And whenever I want to "Upload document" or "Add new directory", I will be routed to _`http://alexluu.csbrandeis.org/flat_latest/login/?next=/flat_latest/addnamespace/`_ or _`http://alexluu.csbrandeis.org/flat_latest/login/?next=/flat_latest/upload/`_ respectively, and therefore cannot upload or add anything.

As I have both consistent and inconsistent instances of FLAT on my sandbox server, I suspect the root cause of this problem may come from my sandbox server but I haven't seen any clues yet.  Do you have any ideas about this?

Best,
Alex

**Comment by luutuntin** [comment]
Now I use another computer to open the problematic instance of FLAT and everything is OK. So the problem is probably caused by some cached data behind the web browser.

**Comment by proycon** [comment]
So I assume the issue is solved and was a cache problem? It indeed didn't seem familiar to me.

**Comment by luutuntin** [comment]
Yes, the issue only happens when I log in to both  instances of FLAT using the same browser. Thank you.
