### ISSUE TITLE
Error during spelling correction

### ISSUE THREAD

**Issue by proycon** [proycon/flat#163]
As reported by @pirolen:

![Screen Shot 2020-12-01 at 11 04 29 PM](https://user-images.githubusercontent.com/75427/100889927-fb9d9480-34b7-11eb-8c27-27e66deb858d.png)

I'm trying to reproduce it first.

**Comment by proycon** [comment]
Error reproduces:

firefox:

```
TypeError: $(...).val() is null
    gather_changes http://127.0.0.1:8000/script/flat.editor.js:1563
    editor_submit http://127.0.0.1:8000/script/flat.editor.js:2391
    editor_oninit http://127.0.0.1:8000/script/flat.editor.js:2697
    jQuery 2
flat.editor.js:1460:17
```

chromium:

```
TypeError: Cannot read property 'trim' of null
    at gather_changes (flat.editor.js:1563)
    at editor_submit (flat.editor.js:2391)
    at HTMLButtonElement.<anonymous> (flat.editor.js:2697)
    at HTMLButtonElement.dispatch (jquery-3.1.0.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.1.0.min.js:3)
```

**Comment by proycon** [comment]
It is caused by there not being an association correction set, this problem should be caught and reported properly to the user.

**Comment by proycon** [comment]
@pirolen: This issue should be solved now, in the next FLAT release a proper error will appear instead of the cryptic one you got. In the meantime you can prevent the error by ensuring you have declared a correction set prior to doing any corrections: Tools & Options > Add new annotation Type > Correction

Alternatively, you can configure your FLAT configuration to add a correction set automatically for every document that is opened by setting the ``autodeclare`` and ``initialcorrectionset`` fields, see https://flat.readthedocs.io/en/latest/administration_guide.html#configuration

Ideally the correction set is a URL to an actual set definition, like for example: https://github.com/proycon/folia/blob/master/setdefinitions/spellingcorrection.foliaset.xml   (but any string will do)

**Comment by pirolen** [comment]
Thanks! Configured this now.
Tried annotating again, but the Annotation Editor dialog is not showing up upon clicking a word (it turns yellow though). I am in Annotation Editor mode. (Would it be possible to explicitly show this mode, so that users can always confirm to themselves the mode they are in?)

**Comment by proycon** [comment]
> Tried annotating again, but the Annotation Editor dialog is not showing up upon clicking a word (it turns yellow though).

That sounds like a bug then, although I didn't have it on my end, could you activate the developer tools in your browser (F12) and see if it outputs any javascript errors to the console there?

> Would it be possible to explicitly show this mode, so that users can always confirm to themselves the mode they are in?

Good idea, I just added an issue for that (#164), I could highlight the selected item in the "Modes" menu.

**Comment by pirolen** [comment]
> and see if it outputs any javascript errors to the console there?

flat.editor.js:672 Uncaught ReferenceError: annotation is not defined
    at showeditor (flat.editor.js:672)
    at editor_onclick (flat.editor.js:1363)
    at HTMLDivElement.onfoliaclick (flat.js:54)
    at HTMLDivElement.dispatch (jquery-3.1.0.min.js:3)
    at HTMLDivElement.q.handle (jquery-3.1.0.min.js:3)

But perhaps I still should configure something.


> Good idea, I just added an issue for that (#164), I could highlight the selected item in the "Modes" menu.

Thanks!
Sometimes it is not easy to navigate between the modes, eg. in a small browser window the dropdown part tends to disappear before one can click an item.

**Comment by proycon** [comment]
I fixed the side-issue that popped up, if everything's well. The new FLAT has been released now.
