### ISSUE TITLE
 FoLiA-abby output not getting rendered

### ISSUE THREAD

**Issue by pirolen** [proycon/flat#165]
I don't seem to be able to render this FoLiA document in FLAT, the editor area remains empty.
The XML is converted from Abbyy SDK output using FoLiA-abby.

[b1_2_kap4_p297_img_png_out_abbyy_deu.folia.xml.txt](https://github.com/proycon/flat/files/5647236/b1_2_kap4_p297_img_png_out_abbyy_deu.folia.xml.txt)

**Comment by proycon** [comment]
Right, this was a known issue and is an instance of issue #139 , I'll see to fixing that too.
