### ISSUE TITLE
Questions about Annotation Types

### ISSUE THREAD

**Issue by Kentoseth** [proycon/flat#167]
Hi,

Thank you for taking the time to answer my other query. I have kept that issue open until I am ready to publish my text-to-xml folia script and will link to it.

I am having some trouble with annotation types. I will list my comments/queries below:

1. The first thing I learned is that the documentation is somewhat vague on how to add annotations. Only after digging through both the FLAT and folia repo docs did I realize that I need to create a document for my annotations in a specific format
2. How can existing Annotation Types be removed from the FLAT system via the web UI?
3. How can new Annotation Types be imported locally from the filesystem? (I am assuming this might be possible)

Thanks,

**Comment by proycon** [comment]
> 1. The first thing I learned is that the documentation is somewhat vague on how to add annotations. Only after digging through both 
> the FLAT and folia repo docs did I realize that I need to create a document for my annotations in a specific format

Yes, you're referring to the FoLiA set definitions and defining the vocabulary for the annotations I assume? You indeed need to craete a set definition file for that and host is somewhere online where it is publicly accessible. Your FoLiA document in turn refers to the set definition by URL as part of its declarations section. As you probably already know, In FLAT, you can add a such a declaration from the interface (tools & options -> add an annotatino type).

Perhaps I may need to clarify some things in the documentation if this wasn't clear enough from the current version. I understand it has a bit of a learning curve as there are multiple steps involved.

> 2. How can existing Annotation Types be removed from the FLAT system via the web UI?

I'm not entirely sure I get what you mean. Do you want to completely remove an annotation type that is present in the document? There is a command line tool to do that called ``foliaerase`` to do that, but can't be done from the interace currently.

Or do you mean restricting the list of annotation types in the list when you select "Add an annotation type"? That is not possible currently (it lists all the types that exist), but I'd be open to implementing a feature to restrict that if you wish, as it can indeed be too overwhelming for the end user. However, do note that there is an alternative to manually adding annotation types, you as a FLAT administrator can configure FLAT to automatically declare an annotation type and set and associate it with any document that is opened. See the ``autodeclare`` option in https://flat.readthedocs.io/en/latest/administration_guide.html.

> 3. How can new Annotation Types be imported locally from the filesystem? (I am assuming this might be possible)

No, the vocabularies have to be published somewhere on a public webserver (a github repo will do fine if you use the raw link to the set definition), the document would not be very portable/interpretable if the vocabulary is kept undisclosed.

**Comment by Kentoseth** [comment]
> you're referring to the FoLiA set definitions and defining the vocabulary for the annotations I assume?

Correct. It isn't clear to the user that they need to create a specific type of document to get annotations in the system.

> Do you want to completely remove an annotation type that is present in the document?

I was attempting to get the Part-of-Speech annotation into the system and after 3 attempts, ended up under 'Local Annotations' having 4 Part-of-Speech in the dropdown. I cannot screenshot it because of the way the JS dropdown is, but I think you understand the issue? 

> Or do you mean restricting the list of annotation types in the list when you select "Add an annotation type"?

Not this.

**Comment by proycon** [comment]
> Correct. It isn't clear to the user that they need to create a specific type of document to get annotations in the system.

Good to know, I will attempt to clarify it a bit better in the documentation.

> I was attempting to get the Part-of-Speech annotation into the system and after 3 attempts, ended up under 'Local Annotations' having 4 Part-of-Speech in the dropdown. I cannot screenshot it because of the way the JS dropdown is, but I think you understand the issue?

I see what you mean, there is currently indeed no way to properly remove an annotation from the interface. The ``foliaerase`` tool can do it for you on the command line. We should make it availabel from the interface at some point.
