### ISSUE TITLE
No processor specified for Correction

### ISSUE THREAD

**Issue by proycon** [proycon/flat#170]
Reported by @pirolen:

> After having made a few corrections and annotations in a document, if I try making more corrections anywhere in the document, the message keeps popping up about processor declaration:
> 
> ```
> Editor submission failed: FoLiA Document Server error: FoLiA error in pirolen/FA-b1_3_1_mwtext_ostpreuss_pp109_277_001: [NoDefaultError] No processor specified for <correction>, but the presence of multiple declarations prevents assigning a default
> ```
> 
> ```
> Query was: PROCESSOR name "pirolen" type manual IN PROCESSOR name "FLAT" version "0.9.4" host "138.246.225.16:8000" src "http://138.246.225.16:8000/" IN PROCESSOR name "foliadocserve" version "0.7.4" host "badwver-itservice2.srv.mwn.de" folia_version
> "2.4.2" src "https://github.com/proycon/foliadocserve" EDIT t OF https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/text.foliaset.ttl WITH text "Niederun" datetime now confidence NONE (AS CORRECTION OF
> http://raw.github.com/proycon/folia/master/setdefinitions/spellingcorrection.foliaset.xml WITH class "archaic" datetime now confidence NONE) FOR ID FA-b1_3_1_mwtext_ostpreuss_pp109_277_001.text.div1.p11.s.1.w.11 FORMAT flat RETURN target
> ```
> 
> Adding entities still works, but adding corrections don't. If I open new documents, for a while adding corrections goes well, after a while this message keep occurring.

**Comment by pirolen** [comment]
One such document did not load at all next time I logged in. It either gave the processor-related error (in debug mode), or was endlessly trying to load.

**Comment by proycon** [comment]
I'll have to dive into this, there is already an automatic correction mechanism in the underlying library for similar problems, but this situation pertaining to corrections seems to be slightly different.

That the error reoccurs when you open the document again is not unexpected. (the endless loading does seem odd)..

**Comment by pirolen** [comment]
I was trying to reproduce this error using different settings extensively. 
Note (to self): For set changes to take effect, the systemd service that runs the foliadocserve has to be fully stopped and started -- mere 'systemctl restart service' does not seem to change them.

What I could observe was that this processor error occurs when both an entity annotation and a character correction are made in the same sentence, and the first annotation I make is on the entity. Regardless of which set definitions I use (yours or mine).

After submitting entity annotations, the sentence where it belongs to fully disappears from the text area of FLAT.  
(I attach a screenshot -- the html is there, but invisible -- hovering over the area shows the infos/added annotation.)

For the text to reappear,  I have to reload the page (or the doc), or change back from the "current" text class -- if it is getting available, sometimes, but in those cases also with 'invisible' html -- to the original text class ("OCR") .
And then, if I try making a correction in the same sentence (second screenshot),  I get the processor error.
After the error occurred, adding corrections does not work anymore in the document. Adding entities is fine.

But if I proceed with the annotations in reverse order (first a token correction, then the entity), in the same sentence, the processor error does not occur.
It also does not occur if I add annotations/corrections in different sentences, i.e., in different parts of the document than where the text disappears after adding an entity annotation.

Additional detail: on one occassion, in Safari, after the severalth webservice restart, I also got the warning: 

"Warning, there are one or more set definitions that could not be loaded. We will continue as usual but this may negatively impact the ability to visualise and edit the afflicted set(s). The set definition(s) are:https://raw.githubusercontent.com/pirolen/folia-resources/main/namedentities.foliaset.xml"

But I am not using this set in the current config at all (i.e., it is not in settings.py).
Can it be that the set definitions don't fully get updated, under specific circumstances?

![Screenshot 2021-03-25 at 17 12 58](https://user-images.githubusercontent.com/56072981/112505851-76ebc480-8d8d-11eb-9dca-125d233b5d70.png)
![Screenshot 2021-03-25 at 17 15 30](https://user-images.githubusercontent.com/56072981/112506439-0abd9080-8d8e-11eb-9699-d3baa1084a46.png)

**Comment by proycon** [comment]
@pirolen  You were referring to this issue perhaps? This is indeed still open and needs to be addressed before we can release FLAT.

**Comment by pirolen** [comment]
Yes, thanks. 
I run a standalone FLAT, thus cannot use the dev version I guess.

**Comment by proycon** [comment]
Without LaMachine you mean (it's in the development version of LaMachine)? When you're not using LaMachine, you can still force a development installation of FLAT with ``pip install git+https://github.com/proycon/foliadocserve`` and ``pip install git+https://github.com/proycon/flat``.

**Comment by pirolen** [comment]
Yes, without LaMachine.
Thanks! Update worked, but the slices view still does not. If I enable slices in the configuration file, I am able to get to the document registry but document opening or uploading returns an error and thus fails.

Further, I get the below types of error,  if I try annotating (un/tokenized) texts.

Editor submission failed: FoLiA Document Server error: FoLiA error in pirolen/FA-mittelalt_bibkat_sample_001: [ValueError] Textclass is not supported for TextContent

Query was: PROCESSOR name "pirolen" type manual IN PROCESSOR name "FLAT" version "1.0" host "138.246.225.16:8000" src "http://138.246.225.16:8000/" IN PROCESSOR name "foliadocserve" version "0.7.6" host "badwver-itservice2.srv.mwn.de" folia_version "2.5.0" src "https://github.com/proycon/foliadocserve" EDIT t OF https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/text.foliaset.ttl WITH text "Summ" textclass "ocr" datetime now confidence NONE (AS CORRECTION OF https://raw.githubusercontent.com/pirolen/folia-resources/main/bibkat_ocr_corrections.foliaset.xml WITH class "other" datetime now confidence NONE) FOR ID FA-mittelalt_bibkat_sample_001.text.div.1.entry.1.term.1.s.1.w.1 FORMAT flat RETURN target

**Comment by proycon** [comment]
Thus far I'm still having difficulties actually reproducing the original problem with the processor error. I wonder if it already got solved by an earlier fix. I'll dig a bit deeper still..

**Comment by proycon** [comment]
I think this is solved now, I corrected some more things and can't reproduce the error.
