### ISSUE TITLE
Questions: Admins, Users, Document Index: deletion / upload with existing filename 

### ISSUE THREAD

**Issue by pirolen** [proycon/flat#171]
Is it possible for a user to delete documents from the Document index?
In the Guidelines (below) it says so, but how does one becomes an admin and can add users/passwords: in settings.py/in the django settings?

Another Q:
if I upload a new document with the same filename that already exists in the Document Index, the file gets overwritten without a warning. Perhaps a warning would be handy.

> 1.2.1 File Management
> The document index provides simple file management operations such as copying, moving and deleting documents. By default these options are disabled except for administators, to enable them for specific users, assign the User may copy documents wherever he/she has write permission and User may delete documents wherever he/she has write permission.

**Comment by pirolen** [comment]
Re: Upload with existing filename:
If there are multiple period-separated items in the filename, they are all stripped upon upload, which can result in identical filenames and thus in overwriting. 
E.g. `myfile.ucto.folia.xml` and `myfile.corr.folia.xml` and `myfile.folia.xml`  all will get the name in the Document Index `myfile.folia.xml` .

**Comment by proycon** [comment]
> Is it possible for a user to delete documents from the Document index?
> In the Guidelines (below) it says so, but how does one becomes an admin and can add users/passwords: in settings.py/in the django settings?

Yes. Upon installation of flat it should have asked for a "superuser", if you log in as that user you can create users/passwords in from the admin page (there's a link to the admin page in the user menu on the far right, if you have permission,  or just add ``/admin`` to the base URL. If you're using LaMachine then FLAT the superuser is "flat" and the default password is also "flat".

> Re: Upload with existing filename:
> If there are multiple period-separated items in the filename, they are all stripped upon upload, which can result in identical filenames and thus in overwriting.
> E.g. myfile.ucto.folia.xml and myfile.corr.folia.xml and myfile.folia.xml all will get the name in the Document Index myfile.folia.xml .

Good point, this should perhaps be clarified in the documetation: FLAT will rename any files you upload to correspond with the document ID in the FoLiA document. So if you have ```<FoLiA xml:id="blah">``` then you get ``blah.folia.xml`` by definition. So if you wnat a different filename: change the document ID.
