### ISSUE TITLE
disable 'direct edit' for markup jobs

### ISSUE THREAD

**Issue by Irishx** [proycon/flat#175]
In many cases the annotation is intended as an additional layer of markup and we do not want to adjust the original text.

Flat is just too flexible and now we can accidently delete a word in in the original text by accident ( i already did this ;-o).

You would want t have a master-setting button to prevent 'direct edits' by annotators.

**Comment by proycon** [comment]
After some investigation, I come to the conclusion that this is already implemented and needs nothing extra. The administrator can set the ``initialeditannotations`` and/or ``allowededitannotation`` parameters in the configuration to restrict the annotatable types. The key here is to simply remove the ``t`` (text) type. 

The edit annotations menu shows all allowed types, even if text is an allowed type, the user can still disable what he wants to see in the editor himself. But it's best if the administrator of the annotation task restricts it.
