### ISSUE TITLE
Using FQL in FLAT

### ISSUE THREAD

**Issue by pirolen** [proycon/flat#184]
When I submit a query in FLAT using the Query Console, I do see the yellow 'Submitted' box on the right, but get no response. It's my first attempt to query a document in this way.
I am not very sure that the queries are well-formed, e.g. would this one be valid and sufficient?

`USE piroska/alienus_test SELECT pos WHERE class = "NOUN" FOR w RETURN target`

What is the output supposed to look like? 
I also tried to use e.g. FORMAT, but nothing changed. 
Thanks for any hints!

**Comment by proycon** [comment]
On 22-11-23 12:22, pirolen wrote:
> When I submit a query in FLAT using the Query Console, I do see the yellow 'Submitted' box on the right, but get no response. It's my first attempt to query a document in this way.
> I am not very sure that the queries are well-formed, e.g. would this one be valid and sufficient?
> 
> `USE piroska/alienus_test SELECT pos WHERE class = "NOUN" FOR w RETURN target`

Yes, that looks okay. But if you want to see the results reflected in the interface then use
the Search option from the Tools & Options menu instead of the Query
Console (they're very similar though). The query console is mostly for
queries that add/edit data.

**Comment by pirolen** [comment]
Thanks! What shall the output of the Search look like? I don't see any changes in the GUI where the document text is :-(

**Comment by proycon** [comment]
Did you try the option "Change perspective showing only the search results"?
