### ISSUE TITLE
Loading ucto file:  Gateway Time-out 

### ISSUE THREAD

**Issue by pirolen** [proycon/flat#187]
https://github.com/LanguageMachines/ucto/issues/90#issuecomment-1719304641

> (I'm having trouble loading the file at all in FLAT currently, so there may be a bug in FLAT.)

did you also get Gateway Time-out error? I think the file is big.  
Is [v0.11.2](https://github.com/proycon/flat/releases/tag/v0.11.2) solving that?  I use docker FLAT.

**Comment by proycon** [comment]
Yes, I got the same indeed. I don't know what caused it yet, the file isn't that big. At some point I did have an (empty) interface and I could select perspective "sentences", that did work.

**Comment by proycon** [comment]
> Is [v0.11.2](https://github.com/proycon/flat/releases/tag/v0.11.2) solving that? I use docker FLAT.

Unfortunately not no, it has no functional changes really.

**Comment by pirolen** [comment]
After repeated Gateway Time-out errors my FLAT instance got unresponsive and could be reactivated only by restarting the container :-(

**Comment by proycon** [comment]
I tried to reproduce but I do get a successful result now with the new FLAT v0.11.2 container (I just published it to docker hub so you can pull it). It's a bit odd because I didn't really change anything. The full perspective loaded for me, albeit truncated and taking a while. The sentence perspective works too. Can you see if running the latest container solves it for you too?

**Comment by pirolen** [comment]
Yes, thanks, files are loading now (although I am not sure if I am using the exact same ones). Will keep testing... there's another issue I need to open though (conll format upload).

**Comment by pirolen** [comment]
I do get this message under certain circumstances, suspectedly when the file is long or when there is something wrong with the set declarations in the file.

**Comment by proycon** [comment]
I finally found and fixed this bug now, it indeed had to do with the file being long and foliadocserve taking a long time to return a reply, the reverse proxy was timing out on it.

The remaining underlying issue remains that foliadocserve is currently clearly not efficient enough for very big documents, but at least replies won't be cut off anymore (unless they exceed 10 minutes now, which probably is way above any user's patience threshold anyway).
