### ISSUE TITLE
Correction set not properly loaded?

### ISSUE THREAD

**Issue by proycon** [proycon/flat#33]
Correction set seems not to load properly. (Bug may be in FLAT, foliadocserve, or even in pynlpl.)

**Comment by mhkuu** [comment]
I created a pull request for loading an initial correction set specified in `settings.py`. 

However, if you specify one in a file, it's also not loaded. I'm not sure why that is though.

**Comment by proycon** [comment]
Thanks! I'll investigate this issue and the pull request asap!

**Comment by proycon** [comment]
Sorry for the delay. The issue was caused by something deeper in the FoLiA library (proycon/pynlpl@345d31b), in turn caused by something in the FoLiA specification that autogenerates part of the library. It has been fixed now in PyNLP v0.9.2 (just released).

Thanks for going through the trouble of trying to fix it!
