### ISSUE TITLE
Errors after updating

### ISSUE THREAD

**Issue by languagerecipes** [proycon/flat#46]
Hi,

I updated our FLAT server (which worked properly before updating) using the command:

`sudo pip install -U FoLiA-Linguistic-Annotation-Tool pynlpl`

now I get a series of error messages when trying to log in to the server: http://dpaste.com/1NPB6FW# 

Can you please help. 

Cheers

**Comment by proycon** [comment]
I can't remember exactly, but weren't you using a virtualenv installation as recommended, rather than a global installation? If so, you have to first activate the virtual environment in the shell (something like ``. env/bin/activate`` and do everything *without* sudo). Also better do ``sudo uninstall FoLiA-Linguistic-Annotation-Tool pynlpl`` to undo this global step and prevent confusion later on.

The error seems to point to a Django compatibility problem because it is using the globally installed Django rather than the one in the virtualenv.

**Comment by proycon** [comment]
I just took a look on your server and it seems you are not using a virtualenv, but are using a global installation indeed (which is okay too), so ignore the previous message.

I'll test that FLAT works for Django 1.10 (which is what you have now and where it seems to break).

**Comment by proycon** [comment]
I'm preparing a new release that solves compatibility issues with the latest Django

**Comment by languagerecipes** [comment]
excellent! thanks.

**Comment by proycon** [comment]
The new FLAT that fixes this issue has just been released (v0.5.1), you can upgrade again using ``sudo pip install -U FoLiA-Linguistic-Annotation-Tool``

Additionaly, the new ``settings.py`` has some changes you will need to copy into your own settings file. Please copy the changes as in ``settings.py`` in commit ad85b8e3f0feaf4a6c519e56f77294b308375f54 , to your version of ``settings.py``. I hope this is evident enough.

**Comment by languagerecipes** [comment]
Thanks Maarten, is this release stable enough or do you expect other
updates soon? cheers

Behrang

On Fri, Sep 2, 2016 at 9:55 PM, Maarten van Gompel <notifications@github.com

**Comment by proycon** [comment]
This one should be good to go, unless we encounter something unexpected again.

**Comment by languagerecipes** [comment]
Still there are some problems when logging into  the server:
Can you please help? (see below)

`Environment:


Request Method: GET
Request URL: http://mwe.phil.hhu.de/login/?next=/

Django Version: 1.10.1
Python Version: 3.4.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'flat.users',
 'flat.modes.viewer',
 'flat.modes.editor',
 'flat.modes.structureeditor')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Template loader postmortem
Django tried loading these templates, in this order:

Using engine :
    This engine did not provide a list of tried templates.



Traceback:

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.4/dist-packages/flat/views.py" in login
  198.         return render(request, 'login.html',{"defaultconfiguration":settings.DEFAULTCONFIGURATION, "configurations":settings.CONFIGURATIONS, "version": settings.VERSION})

File "/usr/local/lib/python3.4/dist-packages/django/shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "/usr/local/lib/python3.4/dist-packages/django/template/loader.py" in render_to_string
  67.         template = get_template(template_name, using=using)

File "/usr/local/lib/python3.4/dist-packages/django/template/loader.py" in get_template
  25.     raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /login/
Exception Value: login.html`

**Comment by proycon** [comment]
This indicates not all of the necessary changes are in your ``settings.py``. Did you copy the changes I made to ``settings.py`` to your own version of settings.py? That's unfortunately a necessary manual step for this upgrade. See https://github.com/proycon/flat/commit/ad85b8e3f0feaf4a6c519e56f77294b308375f54 (last file of the commit). It concerns the ``TEMPLATE=`` statement mostly and an extra import statement at the beginning.

**Comment by languagerecipes** [comment]
Hi Maarten,

I did update the setting.py by adding/removing lines as highlighted  for
setting.py in
https://github.com/proycon/flat/commit/ad85b8e3f0feaf4a6c519e56f77294b308375f54

Cheers

Behrang

On Tue, Sep 6, 2016 at 6:51 PM, Maarten van Gompel <notifications@github.com

**Comment by proycon** [comment]
Do you mean the error still persists despite the changes? Did you restart the apache webserver and the foliadocserve?

**Comment by languagerecipes** [comment]
Hi, OK restarting the server resolved the problem. Now I have to fix Could
not connect to document server!
I guess I need to change some setting somewhere, right?!

Cheers




On Wed, Sep 7, 2016 at 9:57 AM, Maarten van Gompel <notifications@github.com

**Comment by proycon** [comment]
No, the document server is not tied to Apache so it has to be started independently on every upgrade. I'll make it clearer in the update instructions.

Make sure the previous ``foliadocserve`` process is not running anymore and then just start it again as in the instructions in the README.

**Comment by languagerecipes** [comment]
Thanks, the systems looks to work fine.
