### ISSUE TITLE
Bug: when modifyint a span after duplication (N button)

### ISSUE THREAD

**Issue by kercos** [proycon/flat#64]
1. Open http://mwe.phil.hhu.de
2. Login with PARSEME-EU
3. Upload sample file in http://tiny.cc/flat_demo_sample
4. Create new annotation (tag: ID) of two words (using SPAN> button)
5. Click on that annotation and click on button N (new annotation based on current one). Press on SPAN> button and add an additional word. You will see an error similar to the following:

Editor submission failed: FQL Syntax Error: Unexpected RESPAN at position 15 in: ADD entity OF https://github.com/proycon/parseme-support/raw/master/parseme-mwe-en.foliaset.xml WITH class "ID" annotator "kercos" annotatortype "manual" datetime now confidence NONE RESPAN ID Pilot2_ST_English.text.1.s.8.w.8 & ID Pilot2_ST_English.text.1.s.8.w.11 & ID Pilot2_ST_English.text.1.s.8.w.13 FOR SPAN ID Pilot2_ST_English.text.1.s.8.w.8 & ID Pilot2_ST_English.text.1.s.8.w.11 & ID Pilot2_ST_English.text.1.s.8.w.13 FORMAT flat RETURN ancestor-focus

**Comment by proycon** [comment]
Fixed in v0.5.3
