### ISSUE TITLE
bug: embedded annotation of same type not allowed

### ISSUE THREAD

**Issue by kercos** [proycon/flat#67]
1. in sentence 1 of the english sample file, tag "clinic diagnostic service" with OTH
2. click on diagnostic, open the annotation, click on N and deselect clinic
You would expect to see an additional annotation "diagnostic service" tagged with OTH but you will see only one annotation (clinic diagnostic service).

**Comment by proycon** [comment]
Something's wrong there indeed, I can reproduce it, I'll look into it

**Comment by proycon** [comment]
Fixed for v0.6
