### ISSUE TITLE
Problem with permissions assigned to groups and its users 

### ISSUE THREAD

**Issue by languagerecipes** [proycon/flat#78]
It seems permissions that are assigned to a group are not inherited by its members (i.e., users). I have some emails from LL group members who do not have permissions that are assigned to this group of users. Can you please check?

**Comment by proycon** [comment]
Hmm, I didn't explicitly implement any group to user inheritance, I thought it would be a feature of the django framework itself. It'll investigate and implement inheritance if needed.

**Comment by proycon** [comment]
Can you give a specific example where it goes wrong? The django documentation does state it should work like I suspected.

**Comment by languagerecipes** [comment]
Create a fake user.
Assign the user to the LL group.
LL group has privileges such as modifying users, documents, etc. and suppose the assigned user to the LL group.
Now login with the fake user. It does not have all the privileges set to the LL group.
At least there was one instance of this type of problem (I will send you info in an email). After adding privileges to the user *directly* the problem was solved.

**Comment by proycon** [comment]
Hmm.. very peculiar. I can't reproduce it locally; I have a test group and two test users as part of that group. The users have no explicit rights whatsoever and the group has the two file management and read/write permissions. The users can see/edit each other's files and use the file management tools without problem, so the inheritance works as expected  here.

**Comment by languagerecipes** [comment]
Does this have to do anything with the order of creating users and groups? :-/

**Comment by proycon** [comment]
That would be very unlikely. I was also wondering whether it may be a cache issue and perhaps logging out and in again helps, but that too is a very wild guess.
