### ISSUE TITLE
Colors of annotations with same category are different

### ISSUE THREAD

**Issue by ceramisch** [proycon/flat#81]
1. Connect to [PARSEME flat instance](mwe.phil.hhu.de), PORTUGUESE config, username ceramisch
2. Load file [PT-03-DiarioGaucho.tsv](https://drive.google.com/open?id=0B_RmFEvbypP0RHZhUEFjN1dXZWM) using integrated converter
3. Annotate "afastar-se" (1 token) using category NonVMWE, click OK ![screenshot from 2016-10-25 22 31 23](https://cloud.githubusercontent.com/assets/1089490/19703625/c93bab9a-9b04-11e6-90ab-04924a74b811.png)
4. Annotate "mantêm ... amizade" (2 tokens) using category NonVMWE, click OK ![screenshot from 2016-10-25 22 31 40](https://cloud.githubusercontent.com/assets/1089490/19703623/c93910f6-9b04-11e6-9476-312a1038aa1b.png)
5. Colors of both annotations are different ![screenshot from 2016-10-25 22 31 53](https://cloud.githubusercontent.com/assets/1089490/19703624/c93966c8-9b04-11e6-920b-7762a4b3fc26.png)

6. Go to document index and re-open the file, both have now the same color

**Comment by proycon** [comment]
I think the above commit should fix it. Do note that class colours may still change, but if so, it should be consistent for all annotations of that class (colours are assigned based on the frequency of classes, they are reserved for the top-7 classes only as we quickly run out of distinguishable and unambiguous colours)

**Comment by ceramisch** [comment]
OK, I guess the current PARSEME FLAT server is not up-to-date right? Please tell me when you, Behrang or Federico update the server and, if I don't observe the problem again, we can close the issue.

**Comment by proycon** [comment]
Should be solve in v0.6.2, please re-open if it reoccurs.
