### ISSUE TITLE
Back from document annotation to docuemnt index

### ISSUE THREAD

**Issue by kercos** [proycon/flat#83]
I've encounter this issue and thought it would be worth documenting it.
- Login
- Open a document and start annotating it
- Press the back button in the browser (i would expect to be redirected to the document index)

The interface goes dark and says: Loading document on the server...(this may take a while for large documents). I'm not sure how long this operation might take, but after few minutes i still don't see anything.

**Comment by proycon** [comment]
Right, this is a bug I noticed as well. When you press back it takes you back to the latest stage on the last page, at which point the system already prepared the 'loading' screen that you're stuck on when going back. I'll see if I can solve this because it is confusing indeed.
